// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDVFSharp.DataContext;

namespace RDVFSharp.Migrations
{
    [DbContext(typeof(RDVFDataContext))]
    [Migration("20181130203646_AddFights")]
    partial class AddFights
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RDVFSharp.Entities.BaseFight", b =>
                {
                    b.Property<string>("FightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoserId")
                        .IsRequired();

                    b.Property<string>("Room")
                        .IsRequired();

                    b.Property<string>("WinnerId")
                        .IsRequired();

                    b.HasKey("FightId");

                    b.HasIndex("LoserId")
                        .IsUnique();

                    b.HasIndex("WinnerId");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("RDVFSharp.Entities.BaseFighter", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Dexterity");

                    b.Property<int>("Endurance");

                    b.Property<int>("Spellpower");

                    b.Property<int>("Strength");

                    b.Property<int>("Willpower");

                    b.HasKey("Name");

                    b.ToTable("Fighters");
                });

            modelBuilder.Entity("RDVFSharp.Entities.BaseFight", b =>
                {
                    b.HasOne("RDVFSharp.Entities.BaseFight", "Loser")
                        .WithOne()
                        .HasForeignKey("RDVFSharp.Entities.BaseFight", "LoserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RDVFSharp.Entities.BaseFight", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
