// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDVFSharp.DataContext;

namespace RDVFSharp.Migrations
{
    [DbContext(typeof(RDVFDataContext))]
    [Migration("20181120230750_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RDVFSharp.Entities.BaseFighter", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Dexterity");

                    b.Property<int>("Endurance");

                    b.Property<int>("Spellpower");

                    b.Property<int>("Strength");

                    b.Property<int>("Willpower");

                    b.HasKey("Name");

                    b.ToTable("Fighters");
                });
#pragma warning restore 612, 618
        }
    }
}
